### ISSUE TITLE
Please Add some method，like this

### ISSUE THREAD

**Issue by tintinsoft** [WilliCommer/ArrayHelper#1]
Please Add some method，like this 
Unique
Clone
CopyArray(from,Count)
class operator Implicit
class operator Explici
class operator Add
class operator Equal

for example:

http://www.raysoftware.cn/?p=278

thank you!

**Comment by WilliCommer** [comment]
Thank you verry much for your interest and for the link to Wu Daxones's blog.
This is similar to ArrayHelper and some years older. 
For me, the most amazing of TArrayEx is the enumarator. 
I did not know that this will work that way. 
Before I get to your wish list, I must confess that I have only an old Delphi XE2 version.
Therefore 'class operator' do not work properly for me.
I have added the 'Unique' and 'CopyArray'.
'Clone' is usefull for TObject, but not for records and dynamic arrays.
When you assign one array to an other like A := B;
then A is a clone of B, the whole record is copied, not the reference.
See the test source '// Equal' at line 916

问候
Willi
